# Generated by Django 2.1.5 on 2021-09-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210913_0954'),
        ('orders', '0003_auto_20210913_0246'),
    ]

    operations = [
    ]
