# Generated by Django 3.1.1 on 2021-09-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='title',
        ),
        migrations.AddField(
            model_name='products',
            name='prod_name',
            field=models.CharField(default='Soap', max_length=300, verbose_name='Product Name'),
            preserve_default=False,
        ),
    ]
