# Generated by Django 2.1.5 on 2021-09-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='old_price',
        ),
    ]
