# Generated by Django 3.1.1 on 2021-09-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210911_0711'),
        ('products', '0002_auto_20210910_1539'),
    ]

    operations = [
    ]
