# Generated by Django 2.1.5 on 2021-09-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=9),
            preserve_default=False,
        ),
    ]
