# Generated by Django 2.1.5 on 2021-09-17 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_old_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='prod_price',
        ),
    ]
