# Generated by Django 2.1.5 on 2021-09-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210911_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'verbose_name': 'category', 'verbose_name_plural': 'Category'},
        ),
    ]
