# Generated by Django 2.1.5 on 2021-09-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_merge_20210912_0534'),
        ('products', '0003_auto_20210913_0929'),
    ]

    operations = [
    ]
