# Generated by Django 2.1.5 on 2021-09-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210911_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
