# Generated by Django 2.1.5 on 2021-09-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210913_0954'),
        ('products', '0004_auto_20210913_0246'),
    ]

    operations = [
    ]
