# Generated by Django 2.1.5 on 2021-09-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
