# Generated by Django 3.1.1 on 2021-09-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210918_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image3',
        ),
    ]
